### ISSUE TITLE
Appearance : Theme - Selection not saved when app is closed.

### ISSUE THREAD

**Issue by sunstarjeff** [responsively-org/responsively-app#644] opened 2021-11-24 20:46 UTC
User Preferences > Appearance > Theme

Chose "Light Mode".  Selection not saved when app is closed. After a restart of the program, it reverts back to Dark Mode.

# 🐞 bug report

### 🌍 Your Environment

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

**Comment by jjavierdguezas** [comment] 2022-01-10 10:26
Hi @sunstarjeff I think this is a duplicate of #589

**Closed** 2022-01-10 10:28 UTC
Labels: duplicate
