### ISSUE TITLE
App calls focus each page refresh 

### ISSUE THREAD

**Issue by mvaneijgen** [responsively-org/responsively-app#837] opened 2023-02-27 13:41 UTC
# 🐞 bug report

### ✍️ Description

While developing websites I got several windows open. I've BrowserSync running which automatically refreshes the page when something is saved. Since version 1 Responsively calls focus the the app when any pages is refreshed. I'll be updating my todolist and slowing all pages get refreshed one by one and each time the app jumps to the front while I wanted to work in let's say Safari. 

### 🕵🏼‍♂️ Is this a regression?

Don't 'call focus' (bring Responsively to the front) when a page has refreshed. 

### 🔬 Minimal Reproduction

Open any other app. Put the following meta tag into  <head> of the website loaded  in Responsively to have the browser refresh every 5 seconds. Bring the other app to the front (in focus) and notice Responsivly 'calling focus' (jumping in front) every 5 seconds. 

### 🌍 Your Environment

<pre><code>
Responsively Version 1.0.3 (1.0.3)

Chip Apple M2 Pro
Memory 16 GB
macOS Ventura 13.2.1
</code></pre>

**Comment by manojVivek** [comment] 2023-03-01 04:21
@mvaneijgen Do you run the production build or development mode of Responsively? 

This behaviour shouldn't happen if you're using the production build downloaded from: https://responsively.app/download/

Can you please confirm how you're running the app?

**Comment by mvaneijgen** [comment] 2023-03-01 08:12
I don't know which version I had downloaded (probably from Github), but I've downloaded the 'production' version now from your link and the same is happening. Here a screen recording with Responsively v0.9 vs v1 with the <meta http-equiv="refresh" content="5"> notice it coming to front every ~5 seconds 

[![https://youtu.be/3H88iywI-6Q](https://img.youtube.com/vi/3H88iywI-6Q/0.jpg)](https://www.youtube.com/watch?v=3H88iywI-6Q)

**Comment by manojVivek** [comment] 2023-03-01 09:53
That's strange. 
Do you embed browser sync in the web page that you're working on?
In any case, would it be possible for you to share a webpage that reproduces this?

**Comment by mvaneijgen** [comment] 2023-03-01 10:10
To exclude BrowserSync from causing the issue, I've just opened a index.html file with only the following meta tag in it     <meta http-equiv="refresh" content="5"> and opened that. Which also causes the issue. 

1. create index.html file 
2. Add <meta http-equiv="refresh" content="5">
3. Open the file in VS code and launch Live Server to open a server at the location of file https://marketplace.visualstudio.com/items?itemName=ritwickdey.LiveServer
4. Open any other app then Responsively

**Comment by valentinlako** [comment] 2023-03-09 11:14
I have a similar issue too. I'm having an ultrawide monitor, so on my left side I have VSCode then in the right I have the browser and design file. Each time I make changes in VSCode triggering liveserver is taking responsively back to fullscreen

See video here: https://www.loom.com/share/4483272033b54d3d9f259be211e4e590

**Comment by 0xtlt** [comment] 2023-03-22 08:50
I have the same problem, when I save my code, the "hot reload" refresh the page and responsively app trigger a focus on the app

**Comment by paulbrause** [comment] 2023-04-19 21:25
Same issue here.
```
Version: 1.1.0
Electron: 23.1.3
Chrome: 110.0.5481.179
Node.js: 18.12.1
V8: 11.0.226.16-electron.0
OS: Linux x64 6.2.8-arch1-1
```

**Comment by ccchapman** [comment] 2023-04-20 16:24
This is an issue for me too.  The page refreshes in the background and Responsively steals focus.  It is making the app almost unusable.

**Comment by manojVivek** [comment] 2023-05-05 05:00
The root cause has been identified, this will be fixed in the next release.

**Comment by manojVivek** [comment] 2023-05-22 04:26
The fix is live on v1.3.0, please let me know if you still face the issue after the upgrade.

**Comment by mvaneijgen** [comment] 2023-05-22 12:46
It seems to be fix for X amount of minutes, but if you've been working on a project for a while all of a sudden it will start calling focus again.

**Comment by manojVivek** [comment] 2023-05-22 15:18
That's interesting. 🤔 
Can you describe your setup a bit? Do you use multiple Responsively App windows?

**Comment by mvaneijgen** [comment] 2023-05-23 07:34
My bad. It is just happening all the time. As soon as a page refreshes the app calls focus. Tested again with an index.html file with the following meta tag in it `<meta http-equiv="refresh" content="5">`, so nothing seems to be fixed in version 1.3.0 (on my setup at least)

**Comment by mvaneijgen** [comment] 2023-07-25 07:15
Can this issue be opened again? It is still happening on Version 1.6.0

**Comment by mvaneijgen** [comment] 2023-10-31 12:08
No changes vision 1.8.0 any news on this?

**Closed** 2024-09-09 04:34 UTC
