### ISSUE TITLE
Error: -107 

### ISSUE THREAD

**Issue by bennniii** [responsively-org/responsively-app#559] opened 2021-03-07 12:02 UTC
when visiting a webpage without an SSL certificate ([www.goldene-krone.de](http://www.goldene-krone.de)), i'm only presented an "Error: -107" (ERR_SSL-PROTOCOL_ERROR).

i have disabled SSL validation in the settings but the problem remains persistent. 

running ResponsivelyApp 0.15.0 on MacMini (M1, 2020), MacOS 11.2.2 (20D80)

**Comment by jjavierdguezas** [comment] 2021-05-10 10:51
it worked for me...
![image](https://user-images.githubusercontent.com/13673443/117648352-669d7680-b18e-11eb-8ae9-10cdbe66e5eb.png)

**Comment by manojVivek** [comment] 2021-05-10 15:58
Works for me as well.

**Comment by jjavierdguezas** [comment] 2022-10-28 09:41
closing this as no further information has been given and we cannot reproduce it

**Closed by jjavierdguezas** 2022-10-28 09:41 UTC
Labels: more info needed
