### ISSUE TITLE
Modals on the screens are displayed when taking a screenshot

### ISSUE THREAD

**Issue by lkusam** [responsively-org/responsively-app#393] opened 2020-08-13 13:27 UTC
When taking a screenshot of a page with a modal pop up on the screen is  not included in the screen shot. 
Happens to  regular screenshot also quick screen shot. 
---

See the images for details took screenshots using the control center ( Header bar) and individual device screenshot as well as quick screenshot. 

![Materializecss - Full - iPad - 2020-13-8 at 9 23 30 AM](https://user-images.githubusercontent.com/14277407/90139807-d76e4a00-dd46-11ea-9a05-3908d11fce43.png)
![Materializecss - iPad - 2020-13-8 at 9 22 42 AM](https://user-images.githubusercontent.com/14277407/90139811-d89f7700-dd46-11ea-8790-e068171869b8.png)

---

Screenshot of the app during the process

![2020-08-13 09_23_36-Window](https://user-images.githubusercontent.com/14277407/90139976-13091400-dd47-11ea-9cbc-a3a3b2423988.jpg)

You can see that there is modal open on the page which is not included in any of the screenshots. 

Page link : https://materializecss.com/

**Comment by manojVivek** [comment] 2020-08-13 13:47
@lkusam Thanks for raising this. This is already being worked on as part of #385.

For more details on why it is happening: https://github.com/responsively-org/responsively-app/issues/382#issuecomment-670934366

Closing this as a duplicate of #385. Please watch that issue for updates.

**Closed by manojVivek** 2020-08-13 13:47 UTC
