### ISSUE TITLE
Improve the App's crash page to have instructions on how to report the issue. 

### ISSUE THREAD

**Issue by manojVivek** [responsively-org/responsively-app#407] opened 2020-08-20 04:02 UTC
Right now the crash page just shows the error stacktrace as a string in a single line: 
<img width="1138" alt="90673436-21b36780-e22e-11ea-964d-2eceb7b88c2c" src="https://user-images.githubusercontent.com/1283424/90715361-a56d6280-e2c7-11ea-8901-b3d57e91c0b2.png">

The improved version can have the following:
1. Show a clear message that the app has crashed
2. Add instruction stating a Github issue has to be raised with the stack trace.
3. Add a `copy error` button that can copy the error information to the clipboard. And if possible add a link that can take the user to the GitHub create issue page with the content prefilled.

**Comment by gorogoroumaru** [comment] 2020-08-20 08:52
Hello, thanks for this awesome software!
I'm new to contribute and I have no idea about how to show this crash page.
Could you tell me about this?

**Comment by jjavierdguezas** [comment] 2020-08-20 09:46
hi @gorogoroumaru and welcome
from the top of my head: just throw an Error inside any component in the renderer process

**Comment by gorogoroumaru** [comment] 2020-08-20 10:44
Thank you!
I will try.

**Comment by jjavierdguezas** [comment] 2020-08-20 11:36
@gorogoroumaru awesome, should I assign you this issue?

**Comment by gorogoroumaru** [comment] 2020-08-20 13:12
Sorry, @jjavierdguezas.
I couldn't show the crash page.
Could you give me a code example to show this?

**Comment by manojVivek** [comment] 2020-08-20 13:30
@gorogoroumaru Can you please try adding `throw new Error('test');` on https://github.com/responsively-org/responsively-app/blob/master/desktop-app/app/components/Addressinput/index.js#L67

Also, please feel free to join your slack workspace for any questions: https://join.slack.com/t/responsively/shared_invite/zt-h0ouywhs-IIeHj39ymz5IOrgcOa_tRA (edited)

**Comment by jzabala** [comment] 2020-08-20 13:32
@gorogoroumaru the problem is that in `development` we don't show that page. Go to: 

https://github.com/responsively-org/responsively-app/blob/6fd99970e9604fa7a89ca6e5abaf760def48d8a5/desktop-app/app/containers/Root.js#L59

and comment the `if` statement. Now, you can throw an error (`throw new Error('Foo')`) from any component.

Let us know if you want to give this issue a try to assign it to you 🙂

**Comment by gorogoroumaru** [comment] 2020-08-20 13:43
Thank you so much @manojVivek  and @jzabala!
I tried your suggested approach, but the screen blacked out and I cannot see the crash page.
Could you help me?
I'm sorry for asking many times.

**Comment by jzabala** [comment] 2020-08-20 13:53
@gorogoroumaru sure, no worries.

Commenting the if in `Root.js`

![Screen Shot 2020-08-20 at 9 50 34 AM](https://user-images.githubusercontent.com/1315054/90778572-caafa000-e2ca-11ea-809f-e5651f9f2988.png)

Throwing error in `WebView/index.js`

https://github.com/responsively-org/responsively-app/blob/6fd99970e9604fa7a89ca6e5abaf760def48d8a5/desktop-app/app/components/WebView/index.js#L812

I get the error screen:

![Screen Shot 2020-08-20 at 9 51 35 AM](https://user-images.githubusercontent.com/1315054/90778683-eca92280-e2ca-11ea-91bd-6d546d3f2f89.png)

**Comment by gorogoroumaru** [comment] 2020-08-20 13:59
Thank you!
I will make a pull request in a few days.
Could you assign me this issue?

**Comment by jjavierdguezas** [comment] 2020-08-20 14:02
great @gorogoroumaru assigned to you

**Closed** 2020-08-31 21:37 UTC
Labels: enhancement
