### ISSUE TITLE
Disable hot reloading

### ISSUE THREAD

**Issue by mario-amazing** [responsively-org/responsively-app#908] opened 2023-04-26 20:26 UTC
# 🚀 Feature Request/question 
How to disable hot Hot-Reloading?
<img width="1912" alt="image" src="https://user-images.githubusercontent.com/9537753/234694406-98617c1d-f895-4014-bc64-bb35be4094ee.png">

**Comment by manojVivek** [comment] 2023-04-27 01:44
@mario-amazing Can you please be a little more specific? The screenshot doesn't seem to help much as well.

**Comment by mario-amazing** [comment] 2023-04-27 10:36
I can't find a function that disables automatic page reloading after saving the code in the IDE

**Comment by manojVivek** [comment] 2023-04-28 01:53
We don't have an auto-reload functionality implemented (yet) in the v1, so it must be something else in your app that's causing this.

**Comment by mario-amazing** [comment] 2023-05-04 15:51
When update my code, **responsively-app** automatically changes my active window. (don't have the same behavior in GoogleChrome):

https://user-images.githubusercontent.com/9537753/236261369-f838e50d-01ae-46b0-a8c7-fec2bb91dfd1.mov

**Comment by manojVivek** [comment] 2023-05-05 05:01
This is a duplicate of #837. 

The cause has been identified and this will be fixed in the next release.

**Closed by manojVivek** 2023-05-05 05:01 UTC

**Comment by manojVivek** [comment] 2023-05-22 04:26
The fix is live on v1.3.0, please let me know if you still face the issue after the upgrade.
