### ISSUE TITLE
System Error

### ISSUE THREAD

**Issue by PupSpikeChaos** [responsively-org/responsively-app#1259] opened 2024-07-03 06:58 UTC
# 🐞 bug report

### ✍️ Description
System Error Message Upon Installation for the first time. Bar fills up to about 75%, dialog box disappears, then this appears. 

### 🕵🏼‍♂️ Is this a regression?
First time installing application.

### 🔬 Minimal Reproduction
Reinstall app from scratch.

### 🌍 Your Environment
Software Version 1.12.0

OS
Windows 11 Home
Version 23H2
OS Build 22631.3737
Windows Feature Experience Pack 1000.22700.1009.0

<pre><code>

</code></pre>

### 🔥 Exception or Error or Screenshot
![image](https://github.com/responsively-org/responsively-app/assets/18110149/1720590b-e9a9-40de-8d2b-ef30f78aff49)
<pre><code>

</code></pre>

**Comment by manojVivek** [comment] 2024-07-03 07:50
This error has nothing to do with the setup file and is caused by your system configuration. 

Try this solution and it may help: https://www.youtube.com/watch?v=i7ox0dHMYE0

I am closing this as we as Responsively app developers cannot do much about, please re-open if you have any follow-up questions.

**Closed by manojVivek** 2024-07-03 07:50 UTC
