### ISSUE TITLE
Devtools comes on top and obstructs modal and menus

### ISSUE THREAD

**Issue by takuyahara** [responsively-org/responsively-app#1212] opened 2024-03-28 01:17 UTC
# 🐞 bug report

### ✍️ Description

Devtools comes on top and modal and menus are obstructed.

### 🕵🏼‍♂️ Is this a regression?

Not sure, this is my very first time to try this app.

### 🔬 Minimal Reproduction

Do as the following video.

### 🌍 Your Environment

<pre><code>MacBook Air M2
macOS 14.4
ResponsivelyApp 1.10.0
</code></pre>

### 🔥 Exception or Error or Screenshot

https://github.com/responsively-org/responsively-app/assets/46240835/616ddace-be9b-46f7-834d-88ccbc75f6eb

**Comment by SaunakNandi** [comment] 2024-09-25 18:59
@takuyahara looks like your dev tool is in overlay mode

**Comment by violetadev** [comment] 2024-10-12 17:41
Closing since it's not a bug, as @SaunakNandi pointed out

**Closed by violetadev** 2024-10-12 17:41 UTC
Labels: bug
