### ISSUE TITLE
I can't login to Responsively

### ISSUE THREAD

**Issue by senkyo-n-takahashi** [responsively-org/responsively-app#808] opened 2023-02-13 02:23 UTC
I am unable to log in to Responsively, using a Google account.
I am using version release 1.0.1. it is working with Apple silicon (M1).
The information on the console shows
The error message "DOMException: String contains an invalid character" was displayed.
error was displayed. Is it because user information such as name contains non-alphabetic characters (e.g. Kanji)?

**Comment by datverse** [comment] 2023-02-16 05:37
@senkyo-n-takahashi please check #803 
@manojVivek 
In my opinion, the login feature should be remove before it have the "cancel" feature.
This should be remove in next release v1.0.2
Current, sometime I reopen the app it require login again.
Thanks

**Comment by rklos** [comment] 2023-02-18 14:23
+1, I'm experiencing the same issue. I have had to downgrade the app version to be able to use it.
![CleanShot 2023-02-18 at 15 21 48](https://user-images.githubusercontent.com/34719093/219870914-99585b37-72a0-457c-b0a7-abeb7991e9dd.png)

**Comment by BlueBoy6** [comment] 2023-02-21 15:43
Same for me, i'm using MSAL/AzureAD and it doesn't work too.. 
![image](https://user-images.githubusercontent.com/37447009/220391510-4e1be8c7-a4d6-48bf-ae11-5bf2ebd9148b.png)

**Comment by senkyo-n-takahashi** [comment] 2023-02-22 00:56
![CleanShot 2023-02-22 at 09 55 09@2x](https://user-images.githubusercontent.com/81404131/220493074-c96cb876-1585-46ef-a4f5-98ab6c041a96.png)

**Comment by senkyo-n-takahashi** [comment] 2023-02-22 01:01
Google accounts that did not use double byte character as their user name were able to log in.

**Comment by manojVivek** [comment] 2023-02-22 02:36
@senkyo-n-takahashi Thanks for the analysis here, this will be picked up for the next release.

**Comment by rklos** [comment] 2023-05-17 19:36
@manojVivek Where do we stand?

**Comment by manojVivek** [comment] 2023-05-18 03:57
@rklos The unicode issue above has been resolved.
Can you please describe the problem you're facing?

**Comment by rklos** [comment] 2023-05-18 09:35
@manojVivek ok, I have been confused because this issue is still open, so I thought that the problem is still ongoing.

**Comment by manojVivek** [comment] 2023-05-18 10:07
Sorry about that, closing it now.

**Closed by manojVivek** 2023-05-18 10:07 UTC
