### ISSUE TITLE
Photo doesn't show up

### ISSUE THREAD

**Issue by SCallahan101** [responsively-org/responsively-app#250] opened 2020-07-02 23:13 UTC
It showed no images at all but img tags are there.

**Comment by manojVivek** [comment] 2020-07-03 03:56
Hey @SCallahan101, Does it work fine on Chrome? 

If so can you please give a sample URL to test it out?

**Comment by SCallahan101** [comment] 2020-07-03 14:34
Sure,

My original chrome tab show this -
https://gyazo.com/b1229009bcac8f340d877a7c07747479

Your program show this - https://gyazo.com/6f95354fbad940e85952cb111957812f

https://shannon-callahan-web-portfolio.herokuapp.com/Pages/Intro.html



Shannon C.
Thinkful Student
SDSU MPA of 2016
*My native language is American Sign Language. While I am bi-lingual, you
may notice English translation errors. Contact me if you have any questions
or need clarification.*

*"The cure for boredom is curiosity. There is no cure for curiosity."*
*-Dorothy Parker*


*"The world is moved along, not only by the mighty shoves of
its heroes, but also by the aggregate of tiny pushes of each honest
worker." -Helen Keller*


*"In reading the lives of great men, I found that the first victory they
won was over themselves... self-discipline with all of them came first."
- Harry S Truman*

**Comment by jjavierdguezas** [comment] 2020-07-04 15:10
@manojVivek  @SCallahan101 
Inspecting elements in the website provided and comparing them with the ones in Responsively I found out that the images are there. The issue is about that there is no height set in styles or props, and somehow Chrome computes a value (greater than 0px) but Responsively app does not (so 0px eq no img showing)

![image](https://user-images.githubusercontent.com/13673443/86515263-fb6d7000-be17-11ea-8ede-5c8d5c929b24.png)

setting some `height` and the images are showing

![image](https://user-images.githubusercontent.com/13673443/86515399-ea712e80-be18-11ea-8079-9ef74227442a.png)


I haven't found anything related to this in the electron issues 😕

**Comment by SCallahan101** [comment] 2020-07-04 20:22
Interestingly, I discovered a different reason by canceling out my img's
css regarding height. I have it down as max-height: 100%; I guess it did
something different that I'm seeing.

Thanks! Sorry to bother you over something small.


Shannon C.
Thinkful Student
SDSU MPA of 2016
*My native language is American Sign Language. While I am bi-lingual, you
may notice English translation errors. Contact me if you have any questions
or need clarification.*

*"The cure for boredom is curiosity. There is no cure for curiosity."*
*-Dorothy Parker*


*"The world is moved along, not only by the mighty shoves of
its heroes, but also by the aggregate of tiny pushes of each honest
worker." -Helen Keller*


*"In reading the lives of great men, I found that the first victory they
won was over themselves... self-discipline with all of them came first."
- Harry S Truman*

**Comment by jjavierdguezas** [comment] 2020-07-29 15:48
I would like to review this issue now that we upgrade electron and chrome, but the URL no longer shows the same @SCallahan101

**Comment by SCallahan101** [comment] 2020-07-29 22:49
Oh sorry, gyazo limited number of saved photos. Maybe that's why it was
deleted. Do you want me to test it again?


Shannon C.
Thinkful Student
SDSU MPA of 2016
*My native language is American Sign Language. While I am bi-lingual, you
may notice English translation errors. Contact me if you have any questions
or need clarification.*

*"The cure for boredom is curiosity. There is no cure for curiosity."*
*-Dorothy Parker*


*"The world is moved along, not only by the mighty shoves of
its heroes, but also by the aggregate of tiny pushes of each honest
worker." -Helen Keller*


*"In reading the lives of great men, I found that the first victory they
won was over themselves... self-discipline with all of them came first."
- Harry S Truman*

**Comment by jjavierdguezas** [comment] 2020-08-25 15:16
Yes @SCallahan101, it would be nice if you could test it again in order to close this issue or label it properly

**Closed** 2020-10-28 21:59 UTC
Labels: more info needed
