### ISSUE TITLE
FAQ formatting

### ISSUE THREAD

**Issue by KavyaBS123** [responsively-org/responsively-app#1330] opened 2024-10-20 12:06 UTC
Hey @violetadev  the FAQ section is not formatted properly, it can be done, can you please assign me.
![image](https://github.com/user-attachments/assets/51fdd0ea-2292-4e76-984c-e629defa2a2b)

**Comment by vykanand** [comment] 2024-10-20 22:36
I think i can take this task, @KavyaBS123 can you assign this issue to me?
My proposal is to adjust the height and style of the background of the page properly to fit the Faq elements.

**Comment by violetadev** [comment] 2024-10-22 21:33
Hi, please start working on it, no need to assign the issue.

**Comment by karthik-nair-20** [comment] 2024-10-27 03:10
Hi @KavyaBS123 , I can't reproduce this, the dark mode is removed from web?
could you check once

**Closed** 2024-11-22 15:49 UTC
