### ISSUE TITLE
When devtools is right-docked, items above cannot be clicked

### ISSUE THREAD

**Issue by alanw83** [responsively-org/responsively-app#530] opened 2020-11-04 01:02 UTC
# 🐞 (Original) bug report

### ✍️ Description

If I try and open the Live CSS editor when devtools is open it won't all me to open the live css editor. I have to open live css editor then dev tools to have them both open at the same time.

### 🕵🏼‍♂️ Is this a regression?

Live CSS editor was not in previous version

### 🔬 Minimal Reproduction

Open program
Load website
Toggle Live CSS Editor to on
Inspect an element to open dev tools
Attempt to toggle off the Live CSS editor - Hand to click does not appear

### 🔥 Exception or Error or Screenshot

<pre><code>

</code></pre>

see: https://github.com/responsively-org/responsively-app/issues/530#issuecomment-722350840

**Comment by jjavierdguezas** [comment] 2020-11-04 07:02
Hi @alanw83 , I couldn't reproduce it.
This is my environment
```
Version: 0.15.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.18362
```

Could you please share your environment? (Press F1 on the app then click Copy button an paste here)
Could you also share a gif or a video showing the issue?

**Comment by alanw83** [comment] 2020-11-04 23:02
Version: 0.15.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.19041

https://drive.google.com/file/d/1xJvX8Gglxb2y_ybWFXqkXrm_TIbwuSlv/view

Hopefully this works and helps!

**Comment by jjavierdguezas** [comment] 2020-11-05 12:35
Thanks for the info @alanw83 

I keep the devtools docked to the bottom, that is why I couldn't reproduce it. Now I did,

I think you found a more complex issue: **when the devtools is docked to the right side of the app, it seems that it is positioned on top of the elements that are above, preventing them from being clicked**

I mean, not only does the Live CSS Editor toggle button stop working, but all buttons stop working as well. Also, if you make the devtools wider, you won't be able to click on the right side of the navigation bar or the action buttons found there.

cc: @manojVivek 

![devtools issue](https://user-images.githubusercontent.com/13673443/98241777-bdba5880-1f6b-11eb-8251-2e99e77cef21.gif)

**Comment by Zoeinfp** [comment] 2020-12-02 14:20
I was unable to reproduce following those steps because the live css does toggle off ...

Version: 0.15.0
Electron: 9.3.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Windows_NT x64 10.0.17763

![image](https://user-images.githubusercontent.com/15839150/100884284-98106880-34b1-11eb-8751-6d454d9b63dc.png)

**Comment by Zoeinfp** [comment] 2020-12-02 15:29
I can try to set correctly the bounds of the panel for having the buttons available for the user to click.

**Comment by ambermah** [comment] 2021-12-12 19:24
Hello, does this bug still need to be fixed? If so, can I have it assigned to me?

**Comment by manojVivek** [comment] 2021-12-15 02:47
@ambermah Yeah, this is still an issue, would appreciate your help on this.

**Comment by p4nu** [comment] 2022-05-28 15:18
I'll try this too for a while. 🙂

**Closed** 2022-06-13 14:10 UTC
Labels: bug, help wanted, good first issue
