### ISSUE TITLE
Strange issue rendering web font

### ISSUE THREAD

**Issue by frankie-tech** [responsively-org/responsively-app#376] opened 2020-08-04 16:30 UTC
When loading the Google Font WorkSans, [GF Page](https://fonts.google.com/specimen/Work+Sans) & [GitHub Repo](https://github.com/weiweihuanghuang/Work-Sans), the "A" character renders incorrectly. See image:

![image](https://user-images.githubusercontent.com/26461046/89318007-3697d480-d64c-11ea-85f9-afefeb57bfde.png)

If I open the same web page in Chrome, the issue is not there. There is an [issue](https://github.com/weiweihuanghuang/Work-Sans/issues/47) open where it seems other people are having similar issues. This was linked to a number of issues like self-hosting the font, like `.woff2`, or specific `font-weights`. But those issues seem to have been resolved for the most part.

On the fonts official website, there is no rendering issues. See image: 

![image](https://user-images.githubusercontent.com/26461046/89319240-d73ac400-d64d-11ea-8dd7-adea68f08fe5.png)

On Google Fonts, the font has the overlapping render. See image:

![image](https://user-images.githubusercontent.com/26461046/89319128-b4101480-d64d-11ea-830a-9d927504607f.png)

I don't know if this is in the control of the responsively team, but still seems relevant to know about.

Responsively info:
Version: 0.9.0
Electron: 9.1.1
Chrome: 83.0.4103.122
Node.js: 12.14.1
V8: 8.3.110.13-electron.0
OS: Darwin x64 19.6.0

Chrome Version that font is working on:
Version 84.0.4147.105 (Official Build)(64-bit)

Let me know if you need any other version info too 🙂

**Comment by manojVivek** [comment] 2020-08-04 17:34
@frankie-tech It looks more like a bug in the font version and has nothing to do with the app. 

We will rollout Chrome 84 in the future releases and that might fix this on the app. But having said that, the root cause is the font file. 

Please let us know if we can do anything else.
I'm going to close this as we can't do much about it.

**Closed by manojVivek** 2020-08-04 17:34 UTC
